USE [master]
GO
CREATE DATABASE [e-commerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'stock_market', FILENAME = N'D:\e-commerce.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'stock_market_log', FILENAME = N'D:\e-commerce.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [e-commerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [e-commerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [e-commerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [e-commerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [e-commerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [e-commerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [e-commerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [e-commerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [e-commerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [e-commerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [e-commerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [e-commerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [e-commerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [e-commerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [e-commerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [e-commerce] SET  ENABLE_BROKER 
GO

ALTER DATABASE [e-commerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [e-commerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [e-commerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [e-commerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [e-commerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [e-commerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [e-commerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [e-commerce] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [e-commerce] SET  MULTI_USER 
GO

ALTER DATABASE [e-commerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [e-commerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [e-commerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [e-commerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [e-commerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [e-commerce] SET QUERY_STORE = OFF
GO

ALTER DATABASE [e-commerce] SET  READ_WRITE 
GO

